---
    name: ci

    on:
      schedule:
        - cron: '0 8 * * 0'
      workflow_dispatch:

    jobs:
        ci:
            runs-on: ubuntu-latest

            steps:
                - name: Checkout
                  uses: actions/checkout@v7

                - name: Download Release
                  id: download_release
                  uses: robinraju/release-downloader@v1
                  with:
                    repository: 'wezterm/wezterm'
                    tag: 'nightly'
                    fileName: 'WezTerm-windows-nightly.zip*'
                    out-file-path: 'release'

                - name: Get Version
                  id: get_version
                  run: |
                    VERSION=$(unzip -Z1 release/WezTerm-windows-nightly.zip | grep -oE '[0-9]{8}-[0-9]{6}-[0-9a-f]{8,}' | head -n1)
                    echo "version=$VERSION" >> "$GITHUB_OUTPUT"
                    for f in release/WezTerm-windows-nightly.zip*; do
                      mv "$f" "${f/nightly/$VERSION}"
                    done

                - name: Release
                  uses: softprops/action-gh-release@v3
                  with:
                    files: 'release/*'
                    tag_name: ${{ steps.get_version.outputs.version }}
